### ISSUE TITLE
Không Follow được

### ISSUE THREAD

**Issue by 56duong** [56duong/syncio-webapp#100]
![image](https://github.com/56duong/syncio-webapp/assets/77065902/c0981ad9-4404-4fe3-a3da-9695fdc6aeb8)
![image](https://github.com/56duong/syncio-webapp/assets/77065902/225b7b9a-5ea0-4042-9383-3e66a012445f)
![image](https://github.com/56duong/syncio-webapp/assets/77065902/d8787a0f-87cd-466c-8faf-66772edacd66)
![image](https://github.com/56duong/syncio-webapp/assets/77065902/c441b190-9a93-489b-84ab-daa6b1f012d2)

**Comment by Gein11** [comment]
Done
