### ISSUE TITLE
Story lỗi UI

### ISSUE THREAD

**Issue by Vanhuyne** [56duong/syncio-webapp#105]
![Untitled](https://github.com/56duong/syncio-webapp/assets/106498928/00f9b9c4-e05b-4722-87a4-28f77abfb813)

**Comment by 56duong** [comment]
Bên máy mình bình thường
![image](https://github.com/56duong/syncio-webapp/assets/77065902/227ff1f8-ce04-4915-a19e-243a44bfae11)
