### ISSUE TITLE
Chế độ only khi đăng 2 lần only

### ISSUE THREAD

**Issue by Vanhuyne** [56duong/syncio-webapp#140]
Đang bài no cap 
![image](https://github.com/user-attachments/assets/34987436-805d-4f79-9569-111b710a7090)

New feed chưa có bài viết mới
![image](https://github.com/user-attachments/assets/ef1a0cb5-6972-480d-97e8-75c49089d986)

**Comment by 56duong** [comment]
Từ lâu feed đã được chuyển sang dạng hiển thị pop up new post chứ không unshift thẳng vào feed. Do khi người dùng cuộn xuống dưới thì unshift vô nghĩa.
![image](https://github.com/user-attachments/assets/82c274b7-eb70-4624-b358-24f3b8e57df4)

**Comment by 56duong** [comment]
Bài viết private bị lặp được fix tại đây: [df802cf](https://github.com/56duong/syncio-webapp/commit/df802cfa352009f2bc6864fd44a87f973567719d).
Bằng cách thêm GROUP BY trong repository.
