### ISSUE TITLE
Label ở profile hiển thị của currentUser nên khi vào profile của ai cũng sẽ hiển thị label của currentUser

### ISSUE THREAD

**Issue by 56duong** [56duong/syncio-webapp#168]
![image](https://github.com/user-attachments/assets/17d6bb4e-a72c-46cf-ac30-b19338f20ce4)
![image](https://github.com/user-attachments/assets/67ff18db-ac87-4fc6-99e7-ba9f244b6469)

**Comment by CoanhHeo** [comment]
done fix
