### ISSUE TITLE
Hiển thị Profile

### ISSUE THREAD

**Issue by 56duong** [56duong/syncio-webapp#18]
Chưa cần hiển thị danh sách các bài post của cá nhân

**Comment by ndqThuan** [comment]
Đã hoàn thành nhưng chưa push vì đã thay đổi nhiều class trong project. Tôi đang chờ đến tối ngày 31 - tháng 5 để merge tất cả.

**Comment by ndqThuan** [comment]
Đã hoàn thành backend
