### ISSUE TITLE
SEV-3: Thời gian đăng bài viết, cmt sai. Bị sớm 7 tiếng

### ISSUE THREAD

**Issue by 56duong** [56duong/syncio-webapp#227]
![image](https://github.com/user-attachments/assets/b0870345-b59f-49fc-8ec6-ee706e737d9b)

**Comment by 56duong** [comment]
Đã thử fix đăng abif viết ở https://github.com/56duong/syncio-webapp/commit/7f5dc42a955bf170c5cca7ef71e1e48f87e8e82c#:~:text=createdDate%3A%20new%20Date(date.getTime()%20%2D%20date.getTimezoneOffset()%20*%2060000).toISOString()%2C

đợi build lại xem kết quả

**Comment by Gein11** [comment]
problem has been resolved
