### ISSUE TITLE
SEV-4: Lỗi label các element trong web khi chuyển ngôn ngữ từ tiếng Việt sang tiếng Anh

### ISSUE THREAD

**Issue by ndqThuan** [56duong/syncio-webapp#240]
Bước thực hiện:
1 - Chọn ngôn ngữ tiếng Việt trong web
2 - Refresh trang
3- Chọn ngôn ngữ tiếng Anh
4 - Refresh trang.

![image](https://github.com/user-attachments/assets/0bad4b4d-2085-47a4-92b3-ba1fe9e1271b)

**Comment by 56duong** [comment]
Đã cập nhật : [5aee7dd](https://github.com/56duong/syncio-webapp/commit/5aee7dd6da24e4a4797eb5381d0b5d4e4ba92ced)
Đợi build để check lại

**Comment by ndqThuan** [comment]
Label thuộc notification vẫn bị lỗi.

![image](https://github.com/user-attachments/assets/2f705f2a-8c1d-441a-b719-669140c0f043)

**Comment by 56duong** [comment]
Đã update 
![image](https://github.com/user-attachments/assets/ff34bd35-198a-4898-afd8-eaa43307fa00)
