### ISSUE TITLE
SEV-3: Thời gian đăng bài/comment không đúng

### ISSUE THREAD

**Issue by ndqThuan** [56duong/syncio-webapp#242]
Các bước thực hiện:
1 - Comment trong 1 bài viết được đăng từ trước
2 - Refresh trang
3 - Thời gian đăng comment = thời gian đăng post của 1 user

Tôi đã comment 10 phút trước của 1 bài dượcd dăng 7 giờ trước. Kết quả sau khi refresh, comment của tôi chuyển thành "7 giờ".

![Untitled](https://github.com/user-attachments/assets/ed4dd50b-dc5f-4484-9f4f-68a895a6df52)

**Comment by 56duong** [comment]
Hiện trên bản deploy đã không còn bị

**Comment by Gein11** [comment]
Resolved
