### ISSUE TITLE
Thời gian hiển thị bài post có ảnh chậm

### ISSUE THREAD

**Issue by ndqThuan** [56duong/syncio-webapp#243]
Các bài post có ảnh hiển thị chậm mặc dù đã nhìn thấy nhiều lần.
Các bức ảnh này chưa được cache, dẫn đến trải nghiệm người dùng bị ảnh hưởng do phải chờ đợi các ảnh "đã xem" load lại.

**Comment by 56duong** [comment]
Trùng với issue https://github.com/56duong/syncio-webapp/issues/232
