### ISSUE TITLE
SEV-2: Không tìm kiểm user thông quá hình ảnh được

### ISSUE THREAD

**Issue by ndqThuan** [56duong/syncio-webapp#244]
Các bước thực hiện:
1 - Vào chức năng search
2 - Chọn "Bằng hình ảnh"
3 - Tải ảnh cá nhân của 1 user bất kì

Request về localhost nên không sử dụng được.

![image](https://github.com/user-attachments/assets/44f2a66a-4d05-4cdc-90d6-72a6d54cc537)

**Comment by 56duong** [comment]
Nếu chạy local, phải chạy container như mô tả ở commit https://github.com/56duong/syncio-webapp/commit/7024ab3acb2398137d2a3331d402fd2ae6832ee1
Hoặc chuyển url sang https://facerecognition.ashybeach-e9601552.australiaeast.azurecontainerapps.io và storagetype thành firebase, ở frontend trong file environment chuyển production snag true

Test trên bản deploy cho tiện.
Kết quả test trên bản deploy:
![image](https://github.com/user-attachments/assets/c5ebda40-6d1f-4730-8220-82715b3e2b18)
