### ISSUE TITLE
Sử dụng Enter để submit form

### ISSUE THREAD

**Issue by ndqThuan** [56duong/syncio-webapp#245]
Trong các form Log In, Sign Up hay comment. Nút enter không thể sử dụng được, nhiều người có thói quen nhấn enter để submit vì đây được coi như là tiêu chuẩn chung của nhiều website. Không thể sử dụng Enter để submit khiến cho trải nghiệm người dùng giảm đi.

**Comment by 56duong** [comment]
Đã làm: [5aee7dd](https://github.com/56duong/syncio-webapp/commit/5aee7dd6da24e4a4797eb5381d0b5d4e4ba92ced)
