### ISSUE TITLE
SEV-1: Tài khoản đã bị ban có thể tự Active lại

### ISSUE THREAD

**Issue by ndqThuan** [56duong/syncio-webapp#263]
Tài khoản đã bị ban có thể Active lại sau khi đặt lại mật khẩu sử dụng chức năng "Quên mật khẩu".
Vì trong chức năng update mật khẩu user, vẫn chưa check STATUS mà set thẳng STATUS là "ACTIVE".

Các bước thực hiện:
1 - Ban 1 acc để test
2 - Thử đăng nhập lại bằng tài khoản đó (Không được vì đã bị ban)
2 - Vào phần "Quên mật khẩu" và nhập thông tin email
3 - Xác thực email và đặt lại mật khẩu
4 - Đăng nhập vào tài khoản thành công

**Comment by Gein11** [comment]
Resolved
