### ISSUE TITLE
Profile có thể upload avatar khi khác tài khoản

### ISSUE THREAD

**Issue by 56duong** [56duong/syncio-webapp#295]
![image](https://github.com/user-attachments/assets/f1f9536f-2519-416f-85d2-64fe448cf7d8)

**Comment by 56duong** [comment]
Có thể upload và hiện thông báo thành công, nhưng avatar không thay đổi

![image](https://github.com/user-attachments/assets/0423e283-e6bb-4ae1-bf67-6fa50bebac5a)

**Comment by Gein11** [comment]
I'm fixing

**Comment by Gein11** [comment]
Resolved
