### ISSUE TITLE
Request to change to the RoleEntity class to a RoleEntity ENUM

### ISSUE THREAD

**Issue by ndqThuan** [56duong/syncio-webapp#35]
There will always be 2 roles (at the moment) then shouldn't enum is enough to handle the user's role?
There are too many entities in this project, how about changing the name to "RoleUser"?

Plus, we don't have to create another table to store ROLES if there are only 2 rows. Moreover, therer will be no need to add foreign key just to get a USER's role. Just make it another column for USER.

**Comment by ndqThuan** [comment]
Thank you for your quick response, I agree with you.
I would love to make a modification for this issue, though, there are too many classes that need this RoleEntity class.
Do you want me to overhaul the project with the new enum. It won't take long!

**Comment by 56duong** [comment]
My pleasure, but I think we should discuss this with the person who takes responsibility for this feature before making any changes to prevent future problems.

**Comment by 56duong** [comment]
already changed
