### ISSUE TITLE
Đăng ký - Validate

### ISSUE THREAD

**Issue by 56duong** [56duong/syncio-webapp#88]
- [x] Dài hơn 30 kí tự:

![image](https://github.com/56duong/syncio-webapp/assets/77065902/0bc66817-d991-4723-9113-f0ea81ec217a)

- [x] Có kí tự đặc biệt (chỉ cho a-zA-Z0-9_)

![image](https://github.com/56duong/syncio-webapp/assets/77065902/8493f386-dc03-4625-a636-1bb09a112a5f)

- [ ] Gmail có chữ G in hoa

![image](https://github.com/56duong/syncio-webapp/assets/77065902/38ce25a1-0266-4f5a-9841-4f64e4551d66)

- [x] Email đã tồn tại

![image](https://github.com/56duong/syncio-webapp/assets/77065902/e4d01d81-9135-4447-b9b5-b09858718d87)

- [x] Username đã tồn tại

![image](https://github.com/56duong/syncio-webapp/assets/77065902/2bd79137-3d14-4fff-bff9-4623e3ed1e6c)

- [ ] Vừa đăng ký xong thì qua đăng nhập mà không xác nhận qua email, sửa lại thông báo phù hợp

![image](https://github.com/56duong/syncio-webapp/assets/77065902/614b1dae-5a0d-4610-95af-5648a72a61eb)

- [ ] Sau khi sign up và nhấn link xác nhận ỏ gmail, có vẻ chưa thêm ở JwtTokenFilter

![image](https://github.com/56duong/syncio-webapp/assets/77065902/c66d5562-54ee-423e-84ad-f4eff4ea0613)

- [ ] Đăng ký thành công thì không hiện thông báo gì mà lại chuyển thẳng sang Sign in

**Comment by Gein11** [comment]
Sửa lại quá 50 kí tự đặc biệt và bỏ validate định dạng @GMAIL

**Comment by Gein11** [comment]
Sau khi sign up và nhấn link xác nhận ỏ gmail, có vẻ chưa thêm ở JwtTokenFilter. Kiểm tra thì thấy không báo lỗi
