### ISSUE TITLE
Label Shopping liên tục hiện thông báo lỗi do có Date.now() trong url ảnh

### ISSUE THREAD

**Issue by 56duong** [56duong/syncio-webapp#92]
![image](https://github.com/56duong/syncio-webapp/assets/77065902/70568c29-2d9b-415a-b182-4887b72a9eb5)

![image](https://github.com/56duong/syncio-webapp/assets/77065902/1dc03de0-5277-4276-9146-c075061374d2)

**Comment by CoanhHeo** [comment]
Fixed
